language: node_js
node_js:
  - "8"

cache: yarn

notifications:
  - email: false

before_script:
  - yarn global add gulp-cli

deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: master
