language: node_js
node_js:
  - "8"

cache: yarn

notifications:
  - email: false

before_script:
  - openssl aes-256-cbc -K $encrypted_acc47f91f2ed_key -iv $encrypted_acc47f91f2ed_iv -in github_rsa.enc -out ~\/.ssh/github_rsa -d
  - yarn global add gulp-cli

deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: gh-pages
