language: node_js
node_js:
  - "8"

cache: yarn

notifications:
  - email: false

before_script:
  - git config --global user.email webapp+travis@wire.com
  - git config --global user.name "Wire Travis CI"
  - mkdir -p temp
  - openssl aes-256-cbc -K $encrypted_acc47f91f2ed_key -iv $encrypted_acc47f91f2ed_iv -in deploy.enc -out temp/deploy -d
  - chmod 600 temp/deploy
  - eval `ssh-agent -s`
  - ssh-add temp/deploy
  - rm -rf temp
  - yarn global add gulp-cli

deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: master
